### ISSUE TITLE
A Contribution Plan

### ISSUE THREAD

**Issue by Ap0c** [benClar/Site#1]
Some sort of list of tasks to be completed would be handy, so that people who want to contribute know what they're doing. Possibly this could be a todo list in the README ([like this](https://github.com/blog/1375-task-lists-in-gfm-issues-pulls-comments)), or use the issues system and [milestones](https://guides.github.com/features/issues/#filtering).

My first contribution @benClar =).

**Comment by benClar** [comment]
Your contribution was telling me to do something on my own project!?  The cheek! 

Jokes, yes, you are right...  And thanks for coming back to me on the project.  

Heres a first stab at it:

https://github.com/benClar/Site/blob/master/README.md

What do you think?

**Comment by Ap0c** [comment]
Looks good, mind if I go ahead and turn these into issues and/or milestones?

**Comment by benClar** [comment]
Sure, that'd be awesome!

**Comment by Ap0c** [comment]
I don't appear to be able to add labels and milestones to issues. That may be because I only have read privileges on the repo, I'm not quite sure... Either way I've created issues for each of the main tasks. Now if you want to specify what you'd like for each one, you can add comments explaining what needs to be done =).
